/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import Dominio.Empleado;
import Dominio.Sistema;
import javax.swing.JOptionPane;

/**
 *
 * @author fgavello
 */
public class RegistroEmpleado extends javax.swing.JFrame {

    Sistema sistema;

    public RegistroEmpleado(Sistema s) {
        this.sistema = s;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CampoNombre = new javax.swing.JTextField();
        CampoCedula = new javax.swing.JTextField();
        CampoTelefono = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        CampoFecha = new javax.swing.JTextField();
        CampoDireccion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        AgregarEmpleado = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        CampoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoNombreActionPerformed(evt);
            }
        });
        getContentPane().add(CampoNombre);
        CampoNombre.setBounds(202, 35, 128, 26);
        getContentPane().add(CampoCedula);
        CampoCedula.setBounds(202, 73, 128, 26);
        getContentPane().add(CampoTelefono);
        CampoTelefono.setBounds(202, 105, 128, 26);

        jLabel1.setText("Nombre");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(134, 40, 50, 16);

        jLabel2.setText("Cedula");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(141, 73, 43, 16);

        jLabel3.setText("Telefono");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(129, 110, 55, 16);
        getContentPane().add(CampoFecha);
        CampoFecha.setBounds(202, 143, 128, 26);
        getContentPane().add(CampoDireccion);
        CampoDireccion.setBounds(202, 187, 128, 26);

        jLabel5.setText("Año de ingreso");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(89, 143, 95, 16);

        jLabel6.setText("Direccion");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(124, 187, 60, 16);

        AgregarEmpleado.setText("Agregar empleado");
        AgregarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarEmpleadoActionPerformed(evt);
            }
        });
        getContentPane().add(AgregarEmpleado);
        AgregarEmpleado.setBounds(122, 231, 158, 29);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CampoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoNombreActionPerformed

    private void AgregarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarEmpleadoActionPerformed

        try {
            String direccion = CampoDireccion.getText();
            String nombre = CampoNombre.getText();
            String cedula = CampoCedula.getText();
            String telefono = CampoTelefono.getText();
            int añoDeIngreso = Integer.parseInt(CampoFecha.getText());
//            Persona p= new Empleado(direccion, añoDeIngreso, nombre, cedula, telefono);
            Empleado e = new Empleado(direccion, añoDeIngreso, nombre, cedula, telefono);
            if (!sistema.existePersona(cedula)) {
                sistema.agregarEmpleado(e);
                 JOptionPane.showMessageDialog(null, "Empelado registrado", "Exitoso", -1);

            } else {
                JOptionPane.showMessageDialog(null, "Esta persona ya esta en el sistema", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (NumberFormatException e) {
            JOptionPane.showConfirmDialog(null, "Los campos no son correctos", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        
        


    }//GEN-LAST:event_AgregarEmpleadoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarEmpleado;
    private javax.swing.JTextField CampoCedula;
    private javax.swing.JTextField CampoDireccion;
    private javax.swing.JTextField CampoFecha;
    private javax.swing.JTextField CampoNombre;
    private javax.swing.JTextField CampoTelefono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
